Update to 6.6.1
I have been having errors that look like:

ImportError: /home/mark/mambaforge/envs/dev/lib/python3.10/site-packages/PySide6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
/home/mark/mambaforge/envs/dev/lib/python3.10/site-packages/PySide6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
/home/mark/mambaforge/envs/dev/lib/python3.10/site-packages/PySide6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API

making me feel like the ABI isn't super stable